apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: sec-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-read
  namespace: sec-lab
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-read-bind
  namespace: sec-lab
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: sec-lab
roleRef:
  kind: Role
  name: app-read
  apiGroup: rbac.authorization.k8s.io
