name: Trivy Image Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build demo image
        run: docker build -t demoapp:ci ./sample-images

      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'image'
          image-ref: 'demoapp:ci'
          format: 'sarif'
          output: 'trivy.sarif'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      - name: Also save JSON report
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'image'
          image-ref: 'demoapp:ci'
          format: 'json'
          output: 'trivy.json'

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-json
          path: trivy.json
